### ISSUE TITLE
RedisGraph 2.0

### ISSUE THREAD

**Issue by DvirDukhan** [Jonahss/ioredisgraph#14]
Hi @Jonahss 
Thanks for the work on this project!
We are about to officially release 2.0, so I just wanted to give heads up. We had a slight modification on 1.99.7 which changed to the index modifications commands responses. 
In case you have any questions, you can reach me at our repo issues page or directly by mail.
Cheers!
Dvir

**Comment by Jonahss** [comment]
Thanks!
I'll check to see if the 1.99.7 changes affected this repo. The 2.0 changes were already merged to master and @jgillich has been using them.

**Comment by Jonahss** [comment]
Yup. Tests pass against redislabs/redisgraph:2.0.1 on docker hub.
